name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node ./scripts/verify-dev-env.mjs && npx prisma generate"
dev = "bash ../../../scripts/dev-shopify-admin.sh"
